<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AudititemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $audititems = array(
            array('id' => '4','name' => 'Call type','name2' => 'Emergency'),
            array('id' => '5','name' => 'Call type','name2' => 'Urgent'),
            array('id' => '6','name' => 'Call type','name2' => 'Transfer'),
            array('id' => '7','name' => 'Call type','name2' => 'Discharge'),
            array('id' => '8','name' => 'Call type','name2' => 'Other'),
            array('id' => '9','name' => 'AMPDS code','name2' => 'Abdominal Pain / Problems'),
            array('id' => '10','name' => 'AMPDS code','name2' => 'Allergies'),
            array('id' => '11','name' => 'AMPDS code','name2' => 'Animal bites / attacks'),
            array('id' => '12','name' => 'AMPDS code','name2' => 'Assault / Sexual Assault'),
            array('id' => '13','name' => 'AMPDS code','name2' => 'Back Pain (non-traumatic / non-recent)'),
            array('id' => '14','name' => 'AMPDS code','name2' => 'Breathing problems'),
            array('id' => '15','name' => 'AMPDS code','name2' => 'Burns (scalds) / Explosion (blast)'),
            array('id' => '16','name' => 'AMPDS code','name2' => 'Carbon Monoxide / Inhalation / HAZCHEM / CBRN'),
            array('id' => '17','name' => 'AMPDS code','name2' => 'Cardiac or Respiratory Arrest / Death'),
            array('id' => '18','name' => 'AMPDS code','name2' => 'Chest Pain (non-traumatic)'),
            array('id' => '19','name' => 'AMPDS code','name2' => 'Choking'),
            array('id' => '20','name' => 'AMPDS code','name2' => 'Convulsions / Fitting'),
            array('id' => '21','name' => 'AMPDS code','name2' => 'Diabetic Problems'),
            array('id' => '22','name' => 'AMPDS code','name2' => 'Drowning (near) / Diving / SCUBA Accident'),
            array('id' => '23','name' => 'AMPDS code','name2' => 'Electrocution / Lightning'),
            array('id' => '24','name' => 'AMPDS code','name2' => 'Eye Problems / Injuries'),
            array('id' => '25','name' => 'AMPDS code','name2' => 'Falls'),
            array('id' => '26','name' => 'AMPDS code','name2' => 'Headache'),
            array('id' => '27','name' => 'AMPDS code','name2' => 'Heart Problems / AICD'),
            array('id' => '28','name' => 'AMPDS code','name2' => 'Heat / Cold Exposure'),
            array('id' => '29','name' => 'AMPDS code','name2' => 'Haemorrhage / Lacerations'),
            array('id' => '30','name' => 'AMPDS code','name2' => 'Inaccessible Incident / Other Entrapments (Non-vehicle)'),
            array('id' => '31','name' => 'AMPDS code','name2' => 'Overdose / Poisoning (Ingestion)'),
            array('id' => '32','name' => 'AMPDS code','name2' => 'Pregnancy / Childbirth / Miscarraige'),
            array('id' => '33','name' => 'AMPDS code','name2' => 'Psychiatric / Abnormal Behaviour / Suicide Attempt'),
            array('id' => '34','name' => 'AMPDS code','name2' => 'Sick Person (Specific Diagnosis)'),
            array('id' => '35','name' => 'AMPDS code','name2' => 'Stab / Gunshot / Penetrating Trauma'),
            array('id' => '36','name' => 'AMPDS code','name2' => 'Stroke (CVA)'),
            array('id' => '37','name' => 'AMPDS code','name2' => 'Traffic / Transportation Incidents'),
            array('id' => '38','name' => 'AMPDS code','name2' => 'Traumatic Injuries (Specific)'),
            array('id' => '39','name' => 'AMPDS code','name2' => 'Unconscious / Fainting (Near)'),
            array('id' => '40','name' => 'AMPDS code','name2' => 'Unknown Problem (Collapse 3rd Party)'),
            array('id' => '41','name' => 'AMPDS code','name2' => 'Transfer / Interfacility / Paliative Care'),
            array('id' => '42','name' => 'AMPDS code','name2' => 'ACN (Automatic Crash Notification)'),
            array('id' => '43','name' => 'AMPDS code','name2' => 'Health Care Professional Admission'),
            array('id' => '44','name' => 'Airway','name2' => 'Adjuncts - Head Tilt / Chin Lift'),
            array('id' => '45','name' => 'Airway','name2' => 'Adjuncts - Jaw Thrust'),
            array('id' => '46','name' => 'Airway','name2' => 'Adjuncts - NPA'),
            array('id' => '47','name' => 'Airway','name2' => 'Adjuncts - OPA'),
            array('id' => '48','name' => 'Airway','name2' => 'i-GEL'),
            array('id' => '52','name' => 'Airway','name2' => 'King-LT'),
            array('id' => '53','name' => 'Airway','name2' => 'LMA'),
            array('id' => '54','name' => 'Airway - Advanced','name2' => 'Needle Cricothyroidotomy'),
            array('id' => '55','name' => 'Airway','name2' => 'Other supraglottic device'),
            array('id' => '56','name' => 'Airway','name2' => 'Posture (e.g. recovery position)'),
            array('id' => '57','name' => 'Airway - Advanced','name2' => 'RSI / DAI'),
            array('id' => '58','name' => 'Airway','name2' => 'Suction - Handheld'),
            array('id' => '59','name' => 'Airway','name2' => 'Suction - Manual'),
            array('id' => '60','name' => 'Airway','name2' => 'Suction - Motorised (e.g. LSU)'),
            array('id' => '61','name' => 'Airway - Advanced','name2' => 'Surgical Airway'),
            array('id' => '62','name' => 'Breathing','name2' => 'Bag-Valve-Mask'),
            array('id' => '63','name' => 'Breathing - Advanced','name2' => 'Chest Drain - Left'),
            array('id' => '64','name' => 'Breathing - Advanced','name2' => 'Finger thoracostomy - Left'),
            array('id' => '65','name' => 'Breathing - Advanced','name2' => 'Needle Thoracentesis - 2nd ICS MCL - Left'),
            array('id' => '66','name' => 'Breathing - Advanced','name2' => 'Needle Thoracentesis - 5th ICS MAL - Left'),
            array('id' => '67','name' => 'Breathing','name2' => 'Pocket Mask'),
            array('id' => '68','name' => 'Breathing','name2' => 'Ventilator'),
            array('id' => '69','name' => 'Cardiac - Advanced','name2' => 'Cardioversion'),
            array('id' => '70','name' => 'Cardiac','name2' => 'Defibrillation'),
            array('id' => '71','name' => 'Cardiac','name2' => 'ECG - 3 lead'),
            array('id' => '72','name' => 'Cardiac','name2' => 'ECG - 12 lead'),
            array('id' => '73','name' => 'Cardiac - Advanced','name2' => 'Pacing'),
            array('id' => '74','name' => 'Cardiac','name2' => 'Refer PPCI'),
            array('id' => '75','name' => 'Cardiac','name2' => 'ROSC'),
            array('id' => '77','name' => 'Cardiac - Advanced','name2' => 'Thrombolysis'),
            array('id' => '92','name' => 'Patient Assessment - Advanced','name2' => 'Arterial Blood Gas'),
            array('id' => '93','name' => 'Patient Assessment','name2' => 'Blood Sugar'),
            array('id' => '94','name' => 'Airway - Advanced','name2' => 'End Tidal CO2'),
            array('id' => '95','name' => 'Patient Assessment','name2' => 'Heart Rate'),
            array('id' => '96','name' => 'Patient Assessment - Advanced','name2' => 'Invasive Blood Pressure'),
            array('id' => '97','name' => 'Patient Assessment','name2' => 'Non-invasive Blood Pressure'),
            array('id' => '98','name' => 'Patient Assessment','name2' => 'Glasgow Coma Score'),
            array('id' => '99','name' => 'Patient Assessment','name2' => 'Oxygen Saturations'),
            array('id' => '100','name' => 'Patient Assessment','name2' => 'Peak Flow'),
            array('id' => '101','name' => 'Patient Assessment','name2' => 'Respiratory Rate'),
            array('id' => '102','name' => 'Patient Assessment','name2' => 'AVPU'),
            array('id' => '103','name' => 'Patient Assessment','name2' => 'Pupils'),
            array('id' => '104','name' => 'Patient Assessment','name2' => 'Pain Score'),
            array('id' => '105','name' => 'Patient Assessment','name2' => 'Temperature'),
            array('id' => '106','name' => 'Patient Assessment','name2' => 'FAST'),
            array('id' => '107','name' => 'Trauma','name2' => 'Cervical Collar'),
            array('id' => '108','name' => 'Trauma','name2' => 'C-spine clearance - NEXUS'),
            array('id' => '109','name' => 'Trauma','name2' => 'C-spine clearance - Canadian Rules'),
            array('id' => '110','name' => 'Trauma','name2' => 'Spinal board'),
            array('id' => '111','name' => 'Trauma','name2' => 'Vacuum mattress'),
            array('id' => '112','name' => 'Trauma','name2' => 'Vacuum Splint'),
            array('id' => '113','name' => 'Trauma','name2' => 'Box Splint'),
            array('id' => '114','name' => 'Trauma','name2' => 'Traction Splint'),
            array('id' => '115','name' => 'Trauma','name2' => 'Combiboard / Orthopaedic (scoop) Stretcher'),
            array('id' => '116','name' => 'Other','name2' => 'Mental Capacity Issues'),
            array('id' => '117','name' => 'Other','name2' => 'Child / Vulnerable Adult Issues'),
            array('id' => '118','name' => 'Other','name2' => 'Consent issue'),
            array('id' => '119','name' => 'Outcome','name2' => 'ROLE'),
            array('id' => '120','name' => 'Outcome','name2' => 'Death - Certified at ED'),
            array('id' => '121','name' => 'Outcome','name2' => 'Death - Certified at scene (not ROLE)'),
            array('id' => '122','name' => 'Outcome','name2' => 'Death - DNR'),
            array('id' => '123','name' => 'Outcome','name2' => 'Hospital - ED'),
            array('id' => '124','name' => 'Outcome','name2' => 'Hospital - Other'),
            array('id' => '125','name' => 'Outcome','name2' => 'HEMS'),
            array('id' => '126','name' => 'Outcome','name2' => 'Discharged at Scene'),
            array('id' => '127','name' => 'Outcome','name2' => 'Transported by Police'),
            array('id' => '128','name' => 'Outcome','name2' => 'Hospital - Psychiatric Unit'),
            array('id' => '132','name' => 'Drugs','name2' => 'Adenosine'),
            array('id' => '133','name' => 'Drugs','name2' => 'Adrenaline (Epinephrine) 1:1,000'),
            array('id' => '134','name' => 'Drugs','name2' => 'Adrenaline 1:10,000'),
            array('id' => '135','name' => 'Drugs - Advanced','name2' => 'Adrenaline 1:100,000'),
            array('id' => '136','name' => 'Drugs','name2' => 'Alteplase'),
            array('id' => '137','name' => 'Drugs - Advanced','name2' => 'Aminophylline'),
            array('id' => '138','name' => 'Drugs','name2' => 'Amiodarone'),
            array('id' => '139','name' => 'Drugs','name2' => 'Amoxicillin'),
            array('id' => '140','name' => 'Drugs','name2' => 'Aspirin'),
            array('id' => '141','name' => 'Drugs - Advanced','name2' => 'Atenolol'),
            array('id' => '142','name' => 'Drugs - Advanced','name2' => 'Atracurium'),
            array('id' => '143','name' => 'Drugs','name2' => 'Atropine'),
            array('id' => '144','name' => 'Drugs','name2' => 'Benzylpenicillin'),
            array('id' => '145','name' => 'Drugs - Advanced','name2' => 'Bupivicaine'),
            array('id' => '146','name' => 'Drugs - Advanced','name2' => 'Calcium Chloride'),
            array('id' => '147','name' => 'Drugs - Advanced','name2' => 'Cefalinx'),
            array('id' => '148','name' => 'Drugs - Advanced','name2' => 'Cefotaxime'),
            array('id' => '149','name' => 'Drugs - Advanced','name2' => 'Cetirizine'),
            array('id' => '150','name' => 'Drugs - Advanced','name2' => 'Chloramphenical eye preparation'),
            array('id' => '151','name' => 'Drugs','name2' => 'Chlorphenamine'),
            array('id' => '152','name' => 'Drugs - Advanced','name2' => 'Chlorpromazine'),
            array('id' => '153','name' => 'Drugs - Advanced','name2' => 'Ciprofloxacin'),
            array('id' => '154','name' => 'Drugs','name2' => 'Clopedogrel'),
            array('id' => '155','name' => 'Drugs - Advanced','name2' => 'Clotrimazole'),
            array('id' => '156','name' => 'Drugs - Advanced','name2' => 'Co-dydramol'),
            array('id' => '157','name' => 'Drugs - Advancerd','name2' => 'Coamoxiclav'),
            array('id' => '158','name' => 'Drugs - Advanced','name2' => 'Codeine'),
            array('id' => '159','name' => 'Drugs - Advanced','name2' => 'Codeine-Paracetamol combination'),
            array('id' => '160','name' => 'Drugs','name2' => 'Colloid gel solution'),
            array('id' => '161','name' => 'Drugs - Advanced','name2' => 'Cyclimorph'),
            array('id' => '162','name' => 'Drugs - Advanced','name2' => 'Cyclizine'),
            array('id' => '163','name' => 'Drugs - Advanced','name2' => 'Diamorphine'),
            array('id' => '164','name' => 'Drugs','name2' => 'Diazepam'),
            array('id' => '165','name' => 'Drugs - Advanced','name2' => 'Diclofenac'),
            array('id' => '166','name' => 'Drugs - Advanced','name2' => 'Dicobalt edetate'),
            array('id' => '167','name' => 'Drugs - Advanced','name2' => 'Dihydrocodeine'),
            array('id' => '168','name' => 'Drugs - Advanced','name2' => 'DOMPERIDONE'),
            array('id' => '169','name' => 'Drugs - Advanced','name2' => 'DOXYCYCLINE'),
            array('id' => '170','name' => 'Drugs','name2' => 'Enoxaparin'),
            array('id' => '171','name' => 'Drugs - Advanced','name2' => 'Ergometrine maleate'),
            array('id' => '172','name' => 'Drugs - Advanced','name2' => 'Erythromycin'),
            array('id' => '173','name' => 'Drugs - Advanced','name2' => 'Esmolol'),
            array('id' => '174','name' => 'Drugs - Advanced','name2' => 'Etomidate'),
            array('id' => '175','name' => 'Drugs - Advanced','name2' => 'Flucloxacillin'),
            array('id' => '176','name' => 'Drugs - Advanced','name2' => 'Flumazenil'),
            array('id' => '177','name' => 'Drugs - Advanced','name2' => 'Fluorescein sodium'),
            array('id' => '178','name' => 'Drugs','name2' => 'Furosemide'),
            array('id' => '179','name' => 'Drugs - Advanced','name2' => 'Fusidic acid eye preparation'),
            array('id' => '180','name' => 'Drugs','name2' => 'Glucagon'),
            array('id' => '181','name' => 'Drugs','name2' => 'Glucose 10%'),
            array('id' => '182','name' => 'Drugs - Advanced','name2' => 'Glucose 50%'),
            array('id' => '183','name' => 'Drugs','name2' => 'Glucose gel'),
            array('id' => '184','name' => 'Drugs','name2' => 'GTN'),
            array('id' => '185','name' => 'Drugs - Advanced','name2' => 'Haloperidol'),
            array('id' => '186','name' => 'Drugs - Advanced','name2' => 'Heparin (standard unfractionated)'),
            array('id' => '187','name' => 'Drugs','name2' => 'Hydrocortisone'),
            array('id' => '188','name' => 'Drugs','name2' => 'Ibuprofen'),
            array('id' => '189','name' => 'Drugs','name2' => 'Ipratropium Bromide'),
            array('id' => '190','name' => 'Drugs - Advanced','name2' => 'Ketamine'),
            array('id' => '191','name' => 'Drugs - Advanced','name2' => 'Levonorgestrel'),
            array('id' => '192','name' => 'Drugs - Advanced','name2' => 'Lidocaine'),
            array('id' => '193','name' => 'Drugs - Advanced','name2' => 'Lorazepam'),
            array('id' => '194','name' => 'Drugs - Advanced','name2' => 'Magnesium'),
            array('id' => '195','name' => 'Drugs','name2' => 'Metoclopramide'),
            array('id' => '196','name' => 'Drugs - Advanced','name2' => 'Midazolam'),
            array('id' => '197','name' => 'Drugs','name2' => 'Morphine Sulphate'),
            array('id' => '198','name' => 'Drugs','name2' => 'Nalbuphine Hydrochloride'),
            array('id' => '199','name' => 'Drugs','name2' => 'Naloxone Hydrochloride'),
            array('id' => '200','name' => 'Drugs - Advanced','name2' => 'Nitrofurantoin'),
            array('id' => '201','name' => 'Drugs','name2' => 'Nitrous Oxide / Oxygen 50/50'),
            array('id' => '202','name' => 'Drugs - Advanced','name2' => 'Obidoxime Chloride'),
            array('id' => '204','name' => 'Drugs - Advanced','name2' => 'Oral rehydration salts'),
            array('id' => '205','name' => 'Drugs - Advanced','name2' => 'Otosporin ear drops'),
            array('id' => '206','name' => 'Drugs - Advanced','name2' => 'Oxybuprocaine'),
            array('id' => '207','name' => 'Drugs','name2' => 'Oxygen'),
            array('id' => '208','name' => 'Drugs - Advanced','name2' => 'Oxytetracyclin'),
            array('id' => '209','name' => 'Drugs - Advanced','name2' => 'Oxytocin'),
            array('id' => '210','name' => 'Drugs','name2' => 'Paracetemol (oral)'),
            array('id' => '211','name' => 'Drugs - Advanced','name2' => 'Penicillin V'),
            array('id' => '212','name' => 'Drugs - Advanced','name2' => 'Pethidine'),
            array('id' => '213','name' => 'Drugs - Advanced','name2' => 'Phenoxymethylpenicillin'),
            array('id' => '214','name' => 'Drugs - Advanced','name2' => 'Pralidoxime Mesylate'),
            array('id' => '215','name' => 'Drugs','name2' => 'Prednisolone'),
            array('id' => '216','name' => 'Drugs - Advanced','name2' => 'Prochlorperazine'),
            array('id' => '217','name' => 'Drugs - Advanced','name2' => 'Propofol'),
            array('id' => '218','name' => 'Drugs','name2' => 'Reteplase'),
            array('id' => '219','name' => 'Drugs - Advanced','name2' => 'Rocuronium'),
            array('id' => '220','name' => 'Drugs','name2' => 'Salbutamol'),
            array('id' => '221','name' => 'Drugs - Advanced','name2' => 'Sodium Bircarbonate 4.2%'),
            array('id' => '222','name' => 'Drugs - Advanced','name2' => 'Sodium Bircarbonate 8.4%'),
            array('id' => '223','name' => 'Drugs','name2' => 'Sodium Chloride 0.9%'),
            array('id' => '224','name' => 'Drugs - Advanced','name2' => 'Sodium Chloride 5% (Hypertonic Saline)'),
            array('id' => '225','name' => 'Drugs - Advanced','name2' => 'Sodium Lactate'),
            array('id' => '226','name' => 'Drugs - Advanced','name2' => 'Sodium Thiopentone'),
            array('id' => '227','name' => 'Drugs - Advanced','name2' => 'Suxamethonium'),
            array('id' => '228','name' => 'Drugs','name2' => 'Syntometrine'),
            array('id' => '229','name' => 'Drugs','name2' => 'Tenecteplase'),
            array('id' => '230','name' => 'Drugs - Advanced','name2' => 'Terbutaline'),
            array('id' => '231','name' => 'Drugs - Advanced','name2' => 'Tetanus / Low Dose Diptheria Vaccine'),
            array('id' => '232','name' => 'Drugs - Advanced','name2' => 'Tetanus Immunoglobulin'),
            array('id' => '233','name' => 'Drugs - Advanced','name2' => 'Tetracaine (Amethocaine)'),
            array('id' => '234','name' => 'Drugs','name2' => 'Tramadol'),
            array('id' => '235','name' => 'Drugs - Advanced','name2' => 'Trimethoprim'),
            array('id' => '236','name' => 'Drugs - Advanced','name2' => 'Vecuronium'),
            array('id' => '237','name' => 'Drugs','name2' => 'Water for Injection'),
            array('id' => '238','name' => 'Outcome','name2' => 'Refused to travel'),
            array('id' => '239','name' => 'Outcome','name2' => 'Other'),
            array('id' => '240','name' => 'Outcome','name2' => 'AHP Referral'),
            array('id' => '241','name' => 'Outcome','name2' => 'Mental Health Referral'),
            array('id' => '242','name' => 'Outcome','name2' => 'GP referral'),
            array('id' => '243','name' => 'Airway - Advanced','name2' => 'BURP'),
            array('id' => '244','name' => 'Trauma','name2' => 'Pelvic Splint'),
            array('id' => '245','name' => 'Trauma','name2' => 'Tourniquet'),
            array('id' => '246','name' => 'Breathing - Advanced','name2' => 'Chest Drain - Right'),
            array('id' => '247','name' => 'Breathing - Advanced','name2' => 'Needle Thoracentesis - 2nd ICS MCL - Right'),
            array('id' => '248','name' => 'Breathing - Advanced','name2' => 'Needle Thoracentesis - 5th ICS MAL - Right'),
            array('id' => '249','name' => 'Breathing - Advanced','name2' => 'Finger thoracostomy - Right'),
            array('id' => '250','name' => 'Trauma','name2' => 'Lifting Cushion'),
            array('id' => '251','name' => 'AMPDS code','name2' => 'Chest Pain - STEMI'),
            array('id' => '252','name' => 'AMPDS code','name2' => 'Diabetic Problems - Hypoglycaemia'),
            array('id' => '253','name' => 'AMPDS code','name2' => 'Breathing problems - Asthma'),
            array('id' => '254','name' => 'Drugs','name2' => 'Oral carbohydrate'),
            array('id' => '255','name' => 'AMPDS code','name2' => 'Fracture - Neck of Femur'),
            array('id' => '256','name' => 'HART','name2' => 'Breathing Apparatus'),
            array('id' => '257','name' => 'HART','name2' => 'Gas Tight Suit'),
            array('id' => '258','name' => 'HART','name2' => 'CR1'),
            array('id' => '259','name' => 'HART','name2' => 'PRPS'),
            array('id' => '260','name' => 'Patient Assessment - Advanced','name2' => 'Urinalysis'),
            array('id' => '261','name' => 'HART','name2' => 'PSU'),
            array('id' => '262','name' => 'HART','name2' => 'Ballistics'),
            array('id' => '263','name' => 'HART','name2' => 'Water Rescue'),
            array('id' => '264','name' => 'HART','name2' => 'Safe Working at Height'),
            array('id' => '265','name' => 'HART','name2' => 'Confined Space'),
            array('id' => '266','name' => 'HART','name2' => 'MIBS Stretcher'),
            array('id' => '267','name' => 'HART','name2' => 'SKED Stretcher'),
            array('id' => '268','name' => 'HART','name2' => 'Floating Spinal Board'),
            array('id' => '269','name' => 'HART','name2' => 'Basket Stretcher'),
            array('id' => '270','name' => 'HART','name2' => 'NATO Stretcher / Bran Carrier'),
            array('id' => '271','name' => 'HART','name2' => 'Polaris'),
            array('id' => '272','name' => 'HART','name2' => 'HART Bronze Commander'),
            array('id' => '273','name' => 'HART','name2' => 'Entry Control Officer'),
            array('id' => '274','name' => 'HART','name2' => 'HAZMED Advisor'),
            array('id' => '275','name' => 'HART','name2' => 'Forward Command Vehicle Operator'),
            array('id' => '276','name' => 'HART','name2' => 'Multiple Patients'),
            array('id' => '277','name' => 'HART','name2' => 'Major Incident Declared'),
            array('id' => '278','name' => 'Airway - Advanced','name2' => 'Bougie'),
            array('id' => '279','name' => 'Airway - Advanced','name2' => 'Positube'),
            array('id' => '280','name' => 'Patient Assessment','name2' => 'Auscultation'),
            array('id' => '282','name' => 'Drugs - Advanced','name2' => 'Naproxen'),
            array('id' => '283','name' => 'Drugs - Advanced','name2' => 'Amethocaine Gel'),
            array('id' => '284','name' => 'Drugs - Advanced','name2' => 'Amoxicillin'),
            array('id' => '285','name' => 'Drugs - Advanced','name2' => 'Co-amoxiclav'),
            array('id' => '286','name' => 'Drugs - Advanced','name2' => 'Aciclovir'),
            array('id' => '287','name' => 'Drugs - Advanced','name2' => 'Fucithalmic'),
            array('id' => '288','name' => 'Drugs - Advanced','name2' => 'Gaviscon'),
            array('id' => '289','name' => 'Drugs - Advanced','name2' => 'Levnoelle'),
            array('id' => '290','name' => 'Drugs - Advanced','name2' => 'Locorton-vioform'),
            array('id' => '291','name' => 'Drugs - Advanced','name2' => 'Nystatin'),
            array('id' => '292','name' => 'Patient Assessment - Advanced','name2' => 'ENT examination'),
            array('id' => '293','name' => 'Patient Assessment - Advanced','name2' => 'Blood test'),
            array('id' => '294','name' => 'AMPDS code','name2' => 'Anxiety attack'),
            array('id' => '295','name' => 'ECP','name2' => 'Catheterisation - male'),
            array('id' => '296','name' => 'ECP','name2' => 'Nerve block - Ring'),
            array('id' => '297','name' => 'ECP','name2' => 'X-ray request'),
            array('id' => '298','name' => 'ECP','name2' => 'Wound closure - suture'),
            array('id' => '299','name' => 'ECP','name2' => 'Wound closure - tissue adhesive'),
            array('id' => '300','name' => 'ECP','name2' => 'Wound closure - steristrip'),
            array('id' => '301','name' => 'ECP','name2' => 'Nerve block - fascia-illiaca'),
            array('id' => '302','name' => 'ECP','name2' => 'Nerve block - femoral'),
            array('id' => '303','name' => 'ECP','name2' => 'Nerve block - median'),
            array('id' => '304','name' => 'ECP','name2' => 'Nerve block - ulnar'),
            array('id' => '305','name' => 'ECP','name2' => 'Local anaesthesia'),
            array('id' => '306','name' => 'Trauma','name2' => 'Fracture / Dislocation reduction'),
            array('id' => '307','name' => 'Trauma','name2' => 'Kendrick Extrication Device'),
            array('id' => '308','name' => 'ECP','name2' => 'Catheterisation - female'),
            array('id' => '309','name' => 'Drugs','name2' => 'Ondansetron'),
            array('id' => '310','name' => 'Drugs','name2' => 'Tranexamic Acid'),
            array('id' => '311','name' => 'Outcome','name2' => 'Handed over to another crew'),
            array('id' => '312','name' => 'Outcome','name2' => 'Stood down'),
            array('id' => '313','name' => 'Drugs - Advanced','name2' => 'Activated Charcoal'),
            array('id' => '314','name' => 'Patient Assessment - Advanced','name2' => 'Neurological Examination'),
            array('id' => '315','name' => 'Drugs - Advanced','name2' => 'Clarithromycin'),
            array('id' => '316','name' => 'Drugs - Advanced','name2' => 'Compound Macrogol'),
            array('id' => '317','name' => 'Drugs - Advanced','name2' => 'Dexamethasone'),
            array('id' => '319','name' => 'Drugs - Advanced','name2' => 'Loperamide'),
            array('id' => '320','name' => 'Drugs - Advanced','name2' => 'Metronidazole'),
            array('id' => '321','name' => 'Drugs - Advanced','name2' => 'Revaxis'),
            array('id' => '322','name' => 'Outcome','name2' => 'Crew Referral'),
            array('id' => '323','name' => 'ECP','name2' => 'Pregnancy Test'),
            array('id' => '324','name' => 'Drugs - Advanced','name2' => 'Fentanyl'),
            array('id' => '325','name' => 'Patient Assessment - Advanced','name2' => 'Respiratory examination'),
            array('id' => '326','name' => 'Patient Assessment - Advanced','name2' => 'Cardiovascular examination'),
            array('id' => '327','name' => 'Patient Assessment - Advanced','name2' => 'Musculoskeletal examination'),
            array('id' => '328','name' => 'Patient Assessment - Advanced','name2' => 'MEND'),
            array('id' => '329','name' => 'Outcome','name2' => 'ROSC - ED'),
            array('id' => '330','name' => 'Outcome','name2' => 'ROSC - pPCI'),
            array('id' => '331','name' => 'Outcome','name2' => 'ROSC - MTC'),
            array('id' => '332','name' => 'Outcome','name2' => 'Major Trauma Centre'),
            array('id' => '333','name' => 'Outcome','name2' => 'pPCI'),
            array('id' => '334','name' => 'Drugs','name2' => 'Paracetamol (IV)'),
            array('id' => '335','name' => 'Wound closure','name2' => 'Glue'),
            array('id' => '336','name' => 'Patient Assessment - Advanced','name2' => 'Abdominal Examination'),
            array('id' => '337', 'name' => 'Trauma', 'name2' => 'Blast dressing'),
            array('id' => '338', 'name' => 'Trauma', 'name2' => 'Trauma assessment'),
            array('id' => '339', 'name' => 'Drugs - Advanced', 'name2' => 'Blood products'),
            array('id' => '340', 'name' => 'Other', 'name2' => 'Cardiac arrest team leader'),
            array('id' => '341', 'name' => 'Trauma', 'name2' => 'Haemostatic dressing'),
            array('id' => '342', 'name' => 'Trauma', 'name2' => 'OLAES bandage'),
            array('id' => '343', 'name' => 'Trauma', 'name2' => 'Pressure dressing')
          );

        foreach($audititems as $i) {
            DB::table('audititems')->insert($i);
        }
    }
}
